services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    depends_on:
      - database
    environment:
      - ENCRYPTION_KEY=${TM_ENCRYPTION_KEY}
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - VIRTUAL_HOST=${FQDN_TM}
      - CHECK_ORIGIN=true
      - TZ=${TM_TZ}
      - URL_HOST=${FQDN_TM}
      - URL_PORT=443
      - URL_SCHEME=https
    volumes:
      - ./import:/opt/app/import
    labels:
      traefik.enable: "true"
      traefik.http.services.teslamate.loadbalancer.server.port: "4000"
      traefik.http.middlewares.authelia-auth.forwardauth.address: "http://authelia:9091/api/authz/forward-auth"
      traefik.http.middlewares.authelia-auth.forwardauth.trustForwardHeader: "true"
      traefik.http.middlewares.authelia-auth.forwardauth.authResponseHeaders: "Remote-User,Remote-Groups,Remote-Name,Remote-Email"
      traefik.http.routers.teslamate-websocket.rule: "Host(`${FQDN_TM}`) && PathPrefix(`/live/`)"
      traefik.http.routers.teslamate-websocket.entrypoints: "websecure"
      traefik.http.routers.teslamate-websocket.tls: "true"
      traefik.http.routers.teslamate-websocket.service: "teslamate"
      traefik.http.routers.teslamate-websocket.priority: "100"
      traefik.http.routers.teslamate.rule: "Host(`${FQDN_TM}`) && !PathPrefix(`/static`) && !PathPrefix(`/live/`)"
      traefik.http.routers.teslamate.entrypoints: "websecure"
      traefik.http.routers.teslamate.tls: "true"
      traefik.http.routers.teslamate.middlewares: "authelia-auth"
      traefik.http.routers.teslamate.priority: "10"
      traefik.http.routers.teslamate-static.rule: "Host(`${FQDN_TM}`) && PathPrefix(`/static`)"
      traefik.http.routers.teslamate-static.entrypoints: "websecure"
      traefik.http.routers.teslamate-static.tls: "true"
      traefik.http.routers.teslamate-static.service: "teslamate"
      traefik.http.routers.teslamate-static.priority: "90"
    cap_drop:
      - ALL

  database:
    image: postgres:18-trixie
    restart: always
    environment:
      - POSTGRES_USER=${TM_DB_USER}
      - POSTGRES_PASSWORD=${TM_DB_PASS}
      - POSTGRES_DB=${TM_DB_NAME}
    volumes:
      - teslamate-db:/var/lib/postgresql

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - GRAFANA_PASSWD=${GRAFANA_PW}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PW}
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=Remote-User
      - GF_AUTH_PROXY_HEADER_PROPERTY=username
      - GF_AUTH_PROXY_AUTO_SIGN_UP=true
      - GF_AUTH_PROXY_HEADERS=Name:Remote-Name Email:Remote-Email
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_DOMAIN=${FQDN_TM}
      - GF_SERVER_ROOT_URL=https://${FQDN_TM}/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_ENFORCE_DOMAIN=true

    volumes:
      - teslamate-grafana-data:/var/lib/grafana
    labels:
      traefik.enable: "true"
      traefik.http.services.grafana.loadbalancer.server.port: "3000"
      traefik.http.routers.grafana.rule: "Host(`${FQDN_TM}`) && (Path(`/grafana`) || PathPrefix(`/grafana/`))"
      traefik.http.routers.grafana.entrypoints: "websecure"
      traefik.http.routers.grafana.tls: "true"
      traefik.http.routers.grafana.middlewares: "authelia-auth"

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - "127.0.0.1:1883:1883"
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

  proxy:
    image: traefik:v3.6
    restart: always
    command:
      - "--global.sendAnonymousUsage=false"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http3.advertisedPort=443"
      - "--entrypoints.websecure.forwardedHeaders.insecure=true"
    ports:
      - "127.0.0.1:9080:80"
      - "127.0.0.1:9443:443"
    volumes:
      - ./.htpasswd:/auth/.htpasswd
      - /var/run/docker.sock:/var/run/docker.sock:ro

  authelia:
    image: authelia/authelia:latest
    restart: always
    volumes:
      - ./authelia:/config
    environment:
      - TZ=${TM_TZ}
      - FQDN=${FQDN_TM}
      - AUTHELIA_JWT_SECRET=${AUTHELIA_JWT_SECRET}
      - AUTHELIA_SESSION_SECRET=${AUTHELIA_SESSION_SECRET}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_ENCRYPTION_KEY}
    labels:
      traefik.enable: "true"
      traefik.http.routers.authelia.rule: "Host(`auth.sntrserv.net`)"
      traefik.http.routers.authelia.entrypoints: "web"
      traefik.http.services.authelia.loadbalancer.server.port: "9091"

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
