server:
  address: 'tcp://0.0.0.0:9091'

log:
  level: 'info'

jwt_secret: '{{ env "AUTHELIA_JWT_SECRET" }}'

authentication_backend:
  file:
    path: '/config/users_database.yml'

session:
  name: 'authelia_session'
  secret: '{{ env "AUTHELIA_SESSION_SECRET" }}'
  expiration: '720h'
  inactivity: '168h'
  remember_me: '720h'
  cookies:
    - domain: 'sntrserv.net'
      authelia_url: 'https://auth.sntrserv.net'
      default_redirection_url: 'https://tesla.sntrserv.net/'

storage:
  local:
    path: '/config/db.sqlite3'
  encryption_key: '{{ env "AUTHELIA_STORAGE_ENCRYPTION_KEY" }}'

access_control:
  default_policy: 'deny'
  rules:
    - domain: 'tesla.sntrserv.net'
      policy: 'one_factor'
    - domain: 'auth.sntrserv.net'
      policy: 'bypass'

notifier:
  filesystem:
    filename: '/config/notification.txt'